Repository xaynetwork/xayn_discovery_app, pull requests merged in 2022-07, with the labels that each got.

#551 TB-4003 Pull in strings for favorite sources
  application/lib/presentation/constants/translations/translations.i18n.yaml
  application/lib/presentation/constants/translations/translations_de.i18n.yaml
  application/lib/presentation/constants/translations/translations_es.i18n.yaml
  application/lib/presentation/constants/translations/translations_fr.i18n.yaml
  application/lib/presentation/constants/translations/translations_nl.i18n.yaml
  application/lib/presentation/constants/translations/translations_pl.i18n.yaml
Labels: Ready for review ✅

#556 Fix CI not showing failing tests
  application/fastlane/Fastfile
Labels: Ready for review ✅

#553 Fix bronken back press issue with the select source screen
  application/lib/presentation/feed_settings/page/source/widget/add_source_screen.dart
Labels: Ready for review ✅

#561 Remove mirror_repo github workflow
  .github/scripts/mirror.sh
  .github/workflows/mirror_repo.yaml
Labels: Ready for review ✅

#554 TB-3997 track search events analytics
  application/lib/infrastructure/service/analytics/events/search_items_restored_event.dart
  application/lib/infrastructure/service/analytics/events/search_next_batch_query_event.dart
  application/lib/infrastructure/service/analytics/events/search_query_event.dart
  application/lib/presentation/active_search/manager/active_search_manager.dart
Labels: Ready for review ✅, Testing

#563 TB-4013 Adjust menu dialog top padding
  application/lib/presentation/discovery_card/widget/discovery_card_header_menu.dart
Labels: Ready for review ✅, Testing

#558 TB-4012 Use root overlay when showing the discovery card menu dialog
  application/lib/presentation/active_search/widget/active_search.dart
  application/lib/presentation/discovery_card/screen/discovery_card_screen.dart
  application/lib/presentation/discovery_card/widget/dicovery_feed_card.dart
  application/lib/presentation/discovery_card/widget/discovery_card.dart
  application/lib/presentation/discovery_card/widget/discovery_card_static.dart
  application/lib/presentation/discovery_feed/widget/discovery_feed.dart
  application/pubspec.yaml
Labels: Ready for review ✅, Testing

#547 TB-3976 Push notifications deeplinks POC
  application/lib/domain/model/feature.dart
  application/lib/infrastructure/mappers/document_id_payload_mapper.dart
  application/lib/infrastructure/service/analytics/marketing_analytics_service.dart
  application/lib/infrastructure/service/notifications/local_notifications_service.dart
  application/lib/presentation/base_discovery/manager/base_discovery_manager.dart
  application/lib/presentation/constants/keys.dart
  application/lib/presentation/constants/translations/translations.i18n.yaml
  application/lib/presentation/constants/translations/translations_de.i18n.yaml
  application/lib/presentation/constants/translations/translations_es.i18n.yaml
  application/lib/presentation/constants/translations/translations_fr.i18n.yaml
  application/lib/presentation/constants/translations/translations_nl.i18n.yaml
  application/lib/presentation/constants/translations/translations_pl.i18n.yaml
  application/lib/presentation/discovery_feed/widget/discovery_feed.dart
  application/lib/presentation/feature/manager/feature_manager.dart
  application/lib/presentation/navigation/app_navigator.dart
  application/lib/presentation/navigation/deep_link_data.dart
  application/lib/presentation/navigation/deep_link_manager.dart
  application/lib/presentation/navigation/pages.dart
  application/lib/presentation/settings/manager/settings_manager.dart
  application/lib/presentation/settings/manager/settings_state.dart
  application/lib/presentation/settings/settings_screen.dart
  application/lib/presentation/settings/widget/push_notifications_debug_section.dart
  application/pubspec.yaml
  application/test/presentation/settings/manager/settings_manager_test.dart
  application/test/presentation/settings/settings_screen_test.dart
  application/test/test_utils/mocks.dart
Labels: Ready for review ✅

#562 Tb 4015 change country adding tap area
  application/lib/presentation/feed_settings/widget/country_item.dart
  application/test/presentation/feed_settings/widget/country_item_test.dart
Labels: Ready for review ✅

#567 TB-4002 Rename some payment parameters for analytics
  application/lib/infrastructure/service/analytics/events/subscription_action_event.dart
  application/lib/presentation/navigation/pages.dart
  application/lib/presentation/payment/manager/payment_screen_manager.dart
  application/lib/presentation/payment/paywall_screen.dart
  application/test/presentation/payment/manager/page_payment_screen_manager_test.dart
  application/test/presentation/payment/manager/payment_screen_manager_test.dart
Labels: Ready for review ✅

#575 Enable new dislike flow feature for all flavours
  application/lib/domain/model/feature.dart
Labels: Ready for review ✅

#560 Analytics script to check data integrity between amplitude and mixpanel
  development/migrate_amplitude_to_mixpanel/retrieve_data_from_analytics.py
Labels: Ready for review ✅

#578 Do not open gibberish documents
  application/lib/presentation/discovery_card/widget/check_valid_document_mixin.dart
Labels: Ready for review ✅

#574 TB-4028 Add analytics events for the reset of the AI
  application/lib/infrastructure/service/analytics/events/open_reset_ai_window_event.dart
  application/lib/infrastructure/service/analytics/events/reset_ai_action_event.dart
  application/lib/presentation/settings/manager/settings_manager.dart
Labels: Ready for review ✅, Testing

#576 TB-4054 Remove feature flag for new dislike/exclude source flow
  application/lib/domain/model/feature.dart
  application/lib/presentation/discovery_card/manager/discovery_card_manager.dart
  application/lib/presentation/discovery_card/widget/discovery_card_elements.dart
  application/lib/presentation/feature/manager/feature_manager.dart
  application/test/presentation/feature/widget/select_feature_screen_test.dart
Labels: Ready for review ✅, Testing

#572 Tb 4024 upgrade to freezed 2
  application/ios/Podfile
  application/lib/domain/model/extensions/customer_info_extension.dart
  application/lib/domain/model/extensions/feed_market_extension.dart
  application/lib/domain/model/feed/feed_type_markets.dart
  application/lib/domain/model/feed_market/feed_market.dart
  application/lib/domain/model/feed_settings/feed_settings.dart
  application/lib/infrastructure/discovery_engine/use_case/get_local_markets_use_case.dart
  application/lib/infrastructure/mappers/db_entity_to_feed_market_mapper.dart
  application/lib/infrastructure/mappers/feed_settings_mapper.dart
  application/lib/infrastructure/mappers/feed_type_markets_mapper.dart
  application/lib/infrastructure/mappers/purchasable_product_mapper.dart
  application/lib/infrastructure/service/payment/fake_payment_service.dart
  application/lib/infrastructure/service/payment/payment_mock_data.dart
  application/lib/infrastructure/service/payment/payment_service.dart
  application/lib/infrastructure/service/payment/revenue_cat_payment_service.dart
  application/lib/infrastructure/use_case/feed_settings/get_selected_countries_use_case.dart
  application/lib/infrastructure/use_case/feed_settings/get_selected_feed_market_use_case.dart
  application/lib/infrastructure/use_case/feed_settings/save_initial_feed_market_use_case.dart
  application/lib/infrastructure/use_case/feed_settings/save_selected_countries_use_case.dart
  application/lib/infrastructure/use_case/payment/get_subscription_status_use_case.dart
  application/lib/infrastructure/use_case/payment/listen_subscription_status_use_case.dart
  application/lib/infrastructure/use_case/payment/restore_subscription_use_case.dart
  application/lib/infrastructure/use_case/remote_config/check_remote_config_promo_code_use_case.dart
  application/lib/infrastructure/util/discovery_engine_markets.dart
  application/lib/presentation/base_discovery/manager/base_discovery_manager.dart
  application/lib/presentation/base_discovery/manager/discovery_state.dart
  application/pubspec.yaml
  application/test/domain/model/feed_market_test.dart
  application/test/infrastructure/mapper/db_entity_to_feed_market_mapper_test.dart
  application/test/infrastructure/mapper/feed_settings_mapper_test.dart
  application/test/infrastructure/mapper/purchasable_product_mapper_test.dart
  application/test/infrastructure/use_case/feed_settings/get_selected_countries_use_case_test.dart
  application/test/infrastructure/use_case/feed_settings/get_selected_feed_market_use_case_test.dart
  application/test/infrastructure/use_case/feed_settings/save_initial_feed_market_use_case_test.dart
  application/test/infrastructure/use_case/feed_settings/save_selected_countries_use_case_test.dart
  application/test/infrastructure/use_case/payment/get_subscription_status_use_case_test.dart
  application/test/infrastructure/use_case/payment/purchase_subscription_use_case_test.dart
  application/test/infrastructure/use_case/payment/restore_subscription_se_case_test.dart
  application/test/test_utils/dependency_overrides.dart
Labels: Ready for review ✅, Testing

#581 TB-3978 Fix wrong timeAgo displayed in the card
  application/lib/presentation/utils/time_ago.dart
Labels: Ready for review ✅, Testing

#588 TY-3033 Remove visible subscription/trial info
  application/lib/domain/model/feature.dart
  application/lib/presentation/discovery_feed/manager/discovery_feed_manager.dart
  application/lib/presentation/personal_area/personal_area_screen.dart
Labels: PoC
